version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway:7.15.0
    depends_on:
      - db
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:postgresql://db/mydb -user=postgres -password=password migrate
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - flyway
    ports:
      - 8888:8888
volumes:
  db-data:
