version: '3.8'
services:
  db:
    image: postgres
    env_file:
      - ./.env-postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  postgres_admin:
    container_name: postgres_admin
    image: 'dpage/pgadmin4'
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 9000:80
    env_file:
      - ./.env-postgres-admin
  flyway:
    image: flyway/flyway:7.15.0
    depends_on:
      - db
    volumes:
      - ./sql:/flyway/sql
    command: -url=jdbc:postgresql://db/mydb migrate
    env_file:
      - ./.env-flyway
  mongo:
    container_name: mongo_db
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    command: -url=jdbc:postgresql://db/mydb -user=postgres -password=password migrate
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - flyway
    ports:
      - 27017:27017
    env_file:
      - ./.env-mongo

volumes:
  db-data:
  mongo_data: