INSERT INTO db_schema.context (id_context, title, id_user)
VALUES (1, 'Lean UX: Research, Benchmarking, Personas', 1),
       (2, 'Java NLP Intent Recognition', 1),
       (3, 'Git Merge Instructions', 2),
       (4, 'Lombok Auto-Generated Constructor', 2),
       (5, 'Revertir Git Push Force', 3),
       (6, 'Scrolls in Two Directions', 3),
       (7, 'Enlace de Checklist en Descripción', 4),
       (8, 'Configuración Reloj Superpuesto', 4),
       (9, 'Combinaciones de reloj superpuesto', 5),
       (10, 'Tipos de relojes formas', 5),
       (11, 'Puertos y Procesos en Ubuntu', 6),
       (12, 'Cámaras Poco X5 Pro', 6),
       (13, 'Modelo DDD en Programación', 7),
       (14, 'Flyway Validation Error Fix', 7),
       (15, 'Redirect Button with React', 8),
       (16, 'UserIconButton Component Explanation', 8),
       (17, 'Patrón Singleton en Programación', 9),
       (18, 'Software Development Management', 9),
       (19, 'Simulación básica Spotify Java', 10),
       (20, 'Principios Ing. de Software', 10),
       (21, 'Minimize Problem-Solution Gap', 11),
       (22, 'Adjusting CSS Box Shadow', 11),
       (23, 'Car System Design', 12),
       (24, 'Kanban Pros and Cons', 12),
       (25, 'Explicación de principios SOLID', 13),
       (26, 'Kanban: Características y funcionamiento', 13),
       (27, 'WebStorm ESLint Check Command', 14),
       (28, 'Scope Creep: Problema en proyectos', 14),
       (29, 'Detener npm start suspendido', 15),
       (30, 'TopBar Pegajoso con Scroll', 15),
       (31, 'SMART Goal Example', 16),
       (32, 'Implementing Shadows in DefaultTheme', 16),
       (33, 'React Component Testing', 17),
       (34, 'Developer Skills & Experience', 17),
       (35, 'Convert link to appa', 18),
       (36, 'Bibliography Structure in APA', 18),
       (37, 'Docker COPY Error', 19),
       (38, 'Metrics Importance in Automation', 19),
       (39, 'Python Test Execution Error', 20),
       (40, 'Cannot Generate Spotify Tokens', 20);