name: test-and-deploy

on:
  push:
    branches:
      - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'microsoft'
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Install python dependencies for test
        run: |
          pip install fastapi
          pip install whisper
          pip install python-multipart
      - name: Build with gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build
      - name: Copy the build gradle
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build/libs
  azure_vm:
    needs: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Load build
        uses: actions/download-artifact@v3
        with:
          name: Build
      - name: ls -la
        run: |
          ls -la
      - name: Copy .jar, docker compose, and SQLs
        uses: nogsantos/scp-deploy@master
        with:
          src: docker-compose.yml *.jar sql/
          host: ${{ secrets.SSH_HOST }}
          remote: ${{ secrets.SSH_DIR }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}